- library/modules/gsheets/guides/filtering/README.mdx
Fixes one spelling mistake, closes one ']', and generally dips my toes in contributing.
.
.
.
> fix typos in Gsheet documentation

- javascript/reference/events.md
A better understanding of how the feature works.
> chore: Update Listen to Page Router navigation

- javascript/reference/objects.md
> chore: Object reference typo

- library/modules/mapbox/nodes/v2/mapbox-marker.md
> chore(mapbox): typo

- sdk/overview.mdx
- sdk/references/port-types.md
Adding more insight into how the SDK works and what features are available.
I am just starting the PR right now, will keep adding to this and verify that everything is correct before merging.
> feat(sdk): Add reference data for the SDK input/output types

- .github/workflows/test-build.yml
Adding a GitHub Action workflow for making sure the docs site is building.
> chore(ci): Add GH Action workflow

- .github/workflows/test-build.yml
- nodes/basic-elements/video.md
- nodes/ui-controls/text-input.md
Linux/CI is not working the same as Mac/Windows...
> fix: build

- library/modules/mapbox/guides/geocoder.md
> chore: Add Mapbox reverse geocoding example

- package-lock.json
- package.json
Upgrade all dependencies to latest.
```
@docusaurus/core                   ^2.4.1  →   ^2.4.3
@docusaurus/preset-classic         ^2.4.1  →   ^2.4.3
docusaurus-plugin-sass             ^0.2.3  →   ^0.2.5
react-player                      ^2.10.0  →  ^2.13.0
@docusaurus/module-type-aliases    ^2.4.1  →   ^2.4.3
@tsconfig/docusaurus               ^1.0.7  →   ^2.0.1
typescript                         ^4.6.3  →   ^5.2.2
```
> chore: Upgrade packages

- whats-new/2023-10-04.md
> feat: changelog for 2.9.2

- docs/guides/user-interfaces/basics.md
- javascript/reference/component/README.md
- nodes/component-utilities/component-children/README.md
- static/lessons/gettingstarted/lesson_old.html
> fix: hierarchy typo

- .github/workflows/test-build.yml
Upload build artifact on GitHub Action builds
> feat: GH Workflow, upload artifact

- plugins/copy-node-markdowns.js
> fix: Unix build

- nodes/component-utilities/component-object/README.md
Tiny typo. There was a verb missing.
> Update component object

- javascript/reference/seo/README.md
- sidebarsJavascript.js
fix #14
Currently the text is very light, and I don't expect it to be a lot more. Since this is building on top of something else.
> feat: Add SEO JS API

- docs/guides/cloud-data/access-control.md
- nodes/component-utilities/component-object/README.md
A tweak and fixed a typo on the ACL page.
> Small tweaks on ACL page

- nodes/data/cloud-data/cloud-function/README.md
Add note about Cloud Function timeout
> chore: Add note about Cloud Function timeout

- library/modules/chartjs/README.md
Added a missing comma ',' in the example.
Bug fix, feature, docs update, ...
Please link any relevant issues here.
Feel free to include screenshots if it includes visual changes.
Add any other context or screenshots.
> Update ChartJS README.md

- .github/workflows/pages.yaml
- docusaurus.config.js
> feat: Add GitHub Pages workflow

- docusaurus.config.js
Remove Algolia search, lets replace it later with another search that will be more future proof for this project.
> chore: Remove Algolia search
